# Generated by Django 5.1.7 on 2025-03-14 03:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('muscle_group', models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('legs', 'Legs'), ('shoulders', 'Shoulders'), ('arms', 'Arms'), ('core', 'Core'), ('full_body', 'Full Body'), ('cardio', 'Cardio')], max_length=50)),
                ('is_cardio', models.BooleanField(default=False)),
                ('is_custom', models.BooleanField(default=False)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('equipment_needed', models.CharField(blank=True, max_length=100)),
                ('difficulty_level', models.IntegerField(default=1)),
                ('illustration', models.URLField(blank=True)),
                ('video_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
