# Generated by Django 5.1.7 on 2025-03-14 03:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0, help_text='Duration in minutes')),
                ('notes', models.TextField(blank=True)),
                ('calories_burned', models.IntegerField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-start_time'],
                'indexes': [models.Index(fields=['user_id', 'date'], name='workouts_wo_user_id_f1c995_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('set_number', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('weight', models.FloatField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('distance', models.FloatField(blank=True, help_text='Distance in meters', null=True)),
                ('rpe', models.IntegerField(blank=True, help_text='Rate of Perceived Exertion (1-10)', null=True)),
                ('is_warmup', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='workouts.workout')),
            ],
            options={
                'ordering': ['workout', 'exercise', 'set_number'],
                'unique_together': {('workout', 'exercise', 'set_number')},
            },
        ),
    ]
