# Generated by Django 5.1.7 on 2025-03-15 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fooditem',
            new_name='nutrition_f_name_cad16d_idx',
            old_name='nutrition_fo_name_e8a3d0_idx',
        ),
        migrations.RenameIndex(
            model_name='fooditem',
            new_name='nutrition_f_barcode_b3e40d_idx',
            old_name='nutrition_fo_barcode_d66aad_idx',
        ),
    ]
