# Generated by Django 5.1.7 on 2025-03-15 02:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_rename_nutrition_fo_name_e8a3d0_idx_nutrition_f_name_cad16d_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NutritionGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255, unique=True)),
                ('calorie_target', models.IntegerField(default=2000)),
                ('protein_target', models.DecimalField(decimal_places=2, default=150, max_digits=8)),
                ('carbs_target', models.DecimalField(decimal_places=2, default=200, max_digits=8)),
                ('fat_target', models.DecimalField(decimal_places=2, default=65, max_digits=8)),
                ('fiber_target', models.DecimalField(decimal_places=2, default=25, max_digits=8)),
                ('sugar_target', models.DecimalField(decimal_places=2, default=50, max_digits=8)),
                ('sodium_target', models.DecimalField(decimal_places=2, default=2300, max_digits=8)),
                ('goal_type', models.CharField(choices=[('lose', 'Lose Weight'), ('maintain', 'Maintain Weight'), ('gain', 'Gain Weight')], default='maintain', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MealEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('servings', models.DecimalField(decimal_places=2, default=1.0, max_digits=8)),
                ('calories', models.IntegerField()),
                ('protein', models.DecimalField(decimal_places=2, max_digits=8)),
                ('carbs', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fat', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fiber', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('sugar', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('sodium', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_entries', to='nutrition.fooditem')),
                ('meal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_entries', to='nutrition.mealtype')),
            ],
            options={
                'ordering': ['date', 'time'],
                'indexes': [models.Index(fields=['user_id', 'date'], name='nutrition_m_user_id_2873bd_idx'), models.Index(fields=['meal_type'], name='nutrition_m_meal_ty_e128b3_idx')],
            },
        ),
    ]
